name             'devops'
maintainer       'Saritasa'
maintainer_email 'azolotuhin@saritasa.com'
license          'All rights reserved'
description      'Installs/Configures packages and services on DevOps instance'
version          '0.1.0'

depends 'yum'
depends 'jenkins'
depends 'docker'
